var ImieninyArray=new Array(
	new Array(
		"Mieszka, Mieczys³awa, Marii",
		"Izydora, Bazylego, Grzegorza",
		"Arlety, Genowefy, Danuty",
		"Tytusa, Anieli, Eugeniusza",
		"Hanny, Szymona, Edwarda",
		"Kacpra, Melchiora, Baltazara",
		"Juliana, Lucjana, Rajmunda",
		"Seweryna, M¶cis³awa, Juliusza",
		"Marceliny, Marianny, Juliana",
		"Wilhelma, Dobros³awa, Danuty",
		"Honoraty, Teodozjusza, Matyldy",
		"Grety, Arkadiusza, Rajmunda",
		"Bogumi³y, Weroniki, Hilarego",
		"Feliksa, Domos³awa, Niny",
		"Paw³a, Arnolda, Izydora",
		"Marcelego, W³odzimierza, Waldemara",
		"Antoniego, Ro¶cis³awa, Jana",
		"Piotra, Ma³gorzaty",
		"Henryka, Mariusza, Marty",
		"Fabiana, Sebastiana",
		"Agnieszki, Jaros³awa",
		"Anastazego, Wincentego",
		"Ildefonsa, Rajmunda",
		"Felicji, Franciszka, Rafa³a",
		"Paw³a, Mi³osza, Elwiry",
		"Tymoteusza, Micha³a, Tytusa",
		"Przybys³awa, Anieli, Jerzego",
		"Walerego, Radomira, Tomasza",
		"Zdzis³awa, Franciszka, Józefa",
		"Macieja, Martyny, Teofila",
		"Marceli, Ludwiki, Jana"
	),

	new Array(
		"Brygidy, Ignacego, Seweryna",
		"Marii, Mi³os³awa",
		"B³a¿eja, Oskara",
		"Andrzeja, Weroniki, Joanny",
		"Agaty, Adelajdy",
		"Doroty, Bogdana, Paw³a",
		"Ryszarda, Teodora, Romana",
		"Hieronima, Sebastiana, Ireny",
		"Apolonii, Eryki, Cyryla",
		"Elwiry, Jacka, Scholastyki",
		"Lucjana, Olgierda",
		"Eulalii, Rados³awa, Modesta",
		"Grzegorza, Katarzyny",
		"Cyryla, Metodego, Walentego",
		"Jowity, Faustyna, Zygfryda",
		"Danuty, Julianny, Daniela",
		"Aleksego, Zbigniewa, Lukasza",
		"Szymona, Konstancji, Flawiana",
		"Arnolda, Konrada, Marcelego",
		"Leona, Ludomira, Zenobiusza",
		"Eleonory, Fortunata, Roberta",
		"Marty, Ma³gorzaty, Piotra",
		"Romany, Damiana, Polikarpa",
		"Macieja, Bogusza, Sergiusza",
		"Wiktora, Cezarego",
		"Miros³awa, Aleksandra",
		"Gabriela, Anastazji",
		"Romana, Ludomira, Lecha",
		"Lecha, Lutos³awa"
	),

	new Array(
		"Antoniny, Rados³awa, Dawida",
		"Heleny, Halszki, Paw³a",
		"Maryny, Kunegundy, Tycjana",
		"Lucji, Kazimierza, Eugeniusza",
		"Adriana, Fryderyka, Teofila",
		"Ró¿y, Jordana, Agnieszki",
		"Tomasza, Perpetuy, Felicyty",
		"Beaty, Wincentego, Jana",
		"Franciszki, Brunona",
		"Cypriana, Marcela, Aleksandra",
		"Ludos³awa, Konstantyna, Benedykta",
		"Grzegorza, Justyna, Alojzego",
		"Bo¿eny, Krystyny",
		"Leona, Matyldy, £azarza",
		"Longina, Klemensa, Ludwiki",
		"Izabeli, Oktawii, Hilarego",
		"Patryka, Zbigniewa, Gertrudy",
		"Cyryla, Edwarda, Boguchwa³y",
		"Józefa, Bogdana",
		"Klaudii, Eufemii, Maurycego",
		"Lubomira, Benedykta",
		"Katarzyny, Bogus³awa",
		"Pelagii, Oktawiana, Feliksa",
		"Marka, Gabriela, Katarzyny",
		"Marioli, Wieczys³awa, Ireneusza",
		"Larysy, Emanyela, Teodora",
		"Lidii, Ernesta",
		"Anieli, Sykstusa, Jana",
		"Wiktoryna, Helmuta, Eustachego",
		"Anieli, Kwiryna, Leonarda",
		"Beniamina, Dobromierza, Leonarda"
	),

	new Array(
		"Teodory, Gra¿yny, Ireny",
		"W³adys³awa, Franciszka, Teodozji",
		"Ryszarda, Pankracego, Ingi",
		"Izydora, Wac³awa",
		"Ireny, Wincentego",
		"Izoldy, Celestyna, Wilhelma",
		"Rufina, Celestyna, Jana",
		"Cezaryny, Dionizego, Julii",
		"Marii, Dymitra, Heliodora",
		"Micha³a, Makarego",
		"Filipa, Leona",
		"Juliusza, Lubos³awa, Zenona",
		"Przemys³awa, Hermenegildy, Marcina",
		"Bereniki, Waleriana, Justyny",
		"Ludwiny, Wac³awy, Anastazji",
		"Kseni, Cecylii, Bernardety",
		"Rudolfa, Roberta",
		"Bogus³awy, Apoloniusza",
		"Adolfa, Tymona, Leona",
		"Czes³awa, Agnieszki, Mariana",
		"Anzelma, Bartosza, Feliksa",
		"Kai, Leonii, Sotera",
		"Jerzego, Wojciecha",
		"Horacego, Feliksa, Grzegorza",
		"Marka, Jaros³awa, Wasyla",
		"Marzeny, Klaudiusza, Marii",
		"Zyty, Teofila, Felicji",
		"Piotra, Walerii, Witalisa",
		"Rity, Katarzyny, Bogus³awa",
		"Mariana, Donaty, Tamary"
	),

	new Array(
		"Józefa, Jeremiasza, Filipa",
		"Zygmunta, Atanazego, Anatola",
		"Marii, Antoniny",
		"Moniki, Floriana, W³adys³awa",
		"Ireny, Waldemara",
		"Judyty, Jakuba, Filipa",
		"Gizeli, Ludmi³y, Benedykta",
		"Stanis³awa, Lizy, Wiktora",
		"Bo¿ydara, Grzegorza, Karoliny",
		"Izydora, Antoniny, Symeona",
		"Igi, Miry, W³adys³awy",
		"Pankracego, Dominika, Achillesa",
		"Serwacego, Roberta, Glorii",
		"Bonifacego, Dobies³awa, Macieja",
		"Zofii, Nadziei, Izydora",
		"Andrzeja, Jedrzeja, Szymona",
		"Paschalisa, S³awomira, Weroniki",
		"Eryka, Feliksa, Jana",
		"Iwa, Piotra, Celestyna",
		"Bazylego, Bernardyna, Aleksandra",
		"Wiktora, Kryspina, Tymoteusza",
		"Heleny, Wies³awy, Ryty",
		"Iwony, Dezyderego, Kryspina",
		"Joanny, Zuzanny",
		"Grzegorza, Urbana, Magdaleny",
		"Filipa, Pauliny",
		"Augustyna, Juliana, Magdaleny",
		"Jaromira, Justa, Justyny",
		"Magdaleny, Bogumi³y, Urszuli",
		"Ferdynanda, Karola, Jana",
		"Anieli, Petroneli"
	),

	new Array(
		"Justyna, Anieli, Konrada",
		"Marianny, Marcelina, Piotra",
		"Leszka, Tamary, Karola",
		"Kwiryny, Franciszka",
		"Waltera, Bonifacego, Walerii",
		"Norberta, Laurentego, Bogumi³a",
		"Roberta, Wies³awa",
		"Medarda, Maksyma, Seweryna",
		"Pelagii, Dominika, Efrema",
		"Bogumi³a, Ma³gorzaty, Diany",
		"Barnaby, Radomi³a, Feliksa",
		"Janiny, Onufrego, Leona",
		"Lucjana, Antoniego",
		"Bazylego, Elwiry, Micha³a",
		"Wita, Jolanty",
		"Aliny, Benona, Anety",
		"Laury, Marcjana, Alberta",
		"Marka, El¿biety",
		"Gerwazego, Protazego",
		"Diny, Bogny, Florentyny",
		"Alicji, Alojzego",
		"Pauliny, Tomasza, Jana",
		"Wandy, Zenona",
		"Jana, Danuty",
		"Lucji, Wilhelma, Doroty",
		"Jana, Paw³a",
		"Maryli, W³adys³awa, Cyryla",
		"Leona, Ireneusza",
		"Piotra, Paw³a",
		"Emilii, Lucyny"
	),

	new Array(
		"Haliny, Mariana, Marcina",
		"Jagody, Urbana, Marii",
		"Jacka, Anatola, Tomasza",
		"Odona, Malwiny, El¿biety",
		"Marii, Antoniego",
		"Gotarda, Dominiki, Lucji",
		"Cyryla, Estery, Metodego",
		"Edgara, El¿biety, Eugeniusza",
		"Lukrecji, Weroniki, Zenona",
		"Sylwany, Witalisa, Antoniego",
		"Olgi, Kaliny, Benedykta",
		"Jana, Brunona, Bonifacego",
		"Henryka, Kingi, Andrzeja",
		"Ulryka, Bonawentury, Kamila",
		"Henryka, W³odzimierza, Dawida",
		"Mariki, Benity, Eustachego",
		"Anety, Bogdana, Jadwigi",
		"Erwina, Kamila, Szymona",
		"Wincentego, Wodzis³awa, Marcina",
		"Czes³awa, Hieronima, Ma³gorzaty",
		"Daniela, Dalidy, Wawrzyñca",
		"Marii, Magdaleny",
		"Stwosza, Bogny, Brygidy",
		"Kingi, Krystyny",
		"Walentyny, Krzysztofa, Jakuba",
		"Anny, Miros³awy, Gra¿yny",
		"Lilii, Julii, Natalii",
		"Aidy, Marceli, Wiktora",
		"Olafa, Marty, Ludmi³y",
		"Julity, Piotra, Aldony",
		"Ignacego, Lubomira, Heleny"
	),

	new Array(
		"Nadii, Justyna, Juliana",
		"Kariny, Gustawa, Euzebiusza",
		"Lidii, Augusta, Nikodema",
		"Dominika, Protazego, Jana",
		"Oswalda, Marii, Mariana",
		"S³awy, Jakuba, Oktawiana",
		"Kajetana, Doroty, Sykstusa",
		"Cypriana, Emiliana, Dominika",
		"Romana, Ryszarda, Edyty",
		"Borysa, Filomeny, Wawrzyñca",
		"Klary, Zuzanny, Lecha",
		"Innocentego, Lecha, Euzebii",
		"Diany, Hipolita, Poncjana",
		"Alfreda, Euzebiusza, Maksymiliana",
		"Napoleona, Stelii",
		"Rocha, Stefana, Joachima",
		"¯anny, Mirona, Jacka",
		"Ilony, Bronis³awa, Heleny",
		"Boles³awa, Juliana",
		"Bernarda, Samuela, Sobies³awa",
		"Joanny, Kazimiery, Piusa",
		"Cezarego, Tymoteusza",
		"Apolinarego, Filipa",
		"Jerzego, Bartosza, Haliny",
		"Luizy, Ludwika, Józefa",
		"Marii, Aleksandra",
		"Cezarego, Józefa, Moniki",
		"Patrycji, Wyszomira, Augustyna",
		"Beaty, Jana, Sabiny, Racibora",
		"Ró¿y, Szczêsnego, Feliksa",
		"Bogdana, Ramony, Rajmunda"
	),

	new Array(
		"Idziego, Bronis³awa",
		"Juliana, Stefana, Wilhelma",
		"Grzegorza, Izabeli, Szymona",
		"Idy, Julianny, Rozalii, Ró¿y",
		"Doroty, Teodora, Wawrzyñca",
		"Beaty, Eugeniusza",
		"Domos³awy, Melchiora, Reginy",
		"Marii, Adrianny, Serafiny",
		"¦cibora, Sergiusza, Piotra",
		"Lukasza, Aldony, M¶cis³awa",
		"Jacka, Prota, Dagny, Hiacynta",
		"Gwidona, Radzimira, Marii",
		"Eugenii, Aureliusza, Jana",
		"Roksany, Bernarda, Cypriana",
		"Albina, Nikodema, Marii",
		"Edyty, Korneliusza, Cypriana",
		"Franciszka, Roberta, Justyna",
		"Irmy, Stanis³awa, Ireny",
		"Januarego, Konstancji, Teodora",
		"Filipiny, Eustachego, Euzebii",
		"Jonasza, Mateusza, Hipolita",
		"Tomasza, Maurycego, Joachima",
		"Tekli, Bogus³awa, Linusa",
		"Gerarda, Ruperta, Tomiry",
		"Aurelii, W³adys³awa, Kleofasa",
		"Wawrzyñca, Kosmy, Damiana",
		"Wincentego, Mirabeli, Justyny",
		"Wac³awa, Tymona, Marka",
		"Micha³a, Gabriela, Rafa³a",
		"Wery, Honoriusza, Hieronima"
	),

	new Array(
		"Danuty, Remigiusza, Teresy",
		"Teofila, Dionizego, S³awomira",
		"Teresy, Heliodora, Jana",
		"Rozalii, Edwina, Franciszka",
		"Placyda, Apolinarego",
		"Artura, Brunona",
		"Marii, Marka, Mirelli",
		"Pelagii, Brygidy, Walerii",
		"Amolda, Dionizego, Wincentego",
		"Pauliny, Danieli, Leona",
		"Aldony, Aleksandra, Dobromiry",
		"Eustachego, Maksymiliana, Edwina",
		"Geralda, Edwarda, Honorata",
		"Liwii, Kaliksta, Bernarda",
		"Jadwigi, Teresy, Florentyny",
		"Gaw³a, Ambro¿ego",
		"Wiktora, Marity, Ignacego",
		"Juliana, £ukasza",
		"Ziemowita, Jana, Paw³a",
		"Ireny, Kleopatry, Jana",
		"Urszuli, Hilarego, Jakuba",
		"Halki, Filipa, Salomei",
		"Marleny, Seweryna, Igi",
		"Rafa³a, Marcina, Antoniego",
		"Darii, Wilhelminy, Bonifacego",
		"Lucjana, Ewarysta, Damiana",
		"Iwony, Sabiny",
		"Szymona, Tadeusza",
		"Euzebii, Wioletty, Felicjana",
		"Zenobii, Przemys³awa, Edmunda",
		"Urbana, Saturnina, Krzysztofa"
	),

	new Array(
		"WSZYSTKICH ¦WIÊTYCH",
		"Bohdany, Bo¿ydara",
		"Sylwii, Marcina, Huberta",
		"Karola, Olgierda",
		"El¿biety, S³awomira, Dominika",
		"Feliksa, Leonarda, Ziemowita",
		"Antoniego, ¯ytomira, Ernesta",
		"Seweryna, Bogdana, Klaudiusza",
		"Aleksandra, Ludwika, Teodora",
		"Leny, Ludomira, Leona",
		"Marcina, Bat³omieja, Teodora",
		"Renaty, Witolda, Jozafata",
		"Mateusza, Izaaka, Stanis³awa",
		"Rogera, Serafina, Wawrzyñca",
		"Alberta, Leopolda",
		"Gertrudy, Edmunda, Marii",
		"Salomei, Grzegorza, El¿biety",
		"Romana, Klaudyny, Karoliny",
		"Seweryny, Maksyma, Salomei",
		"Anatola, Sedzimira, Rafa³a",
		"Alberta, Janusza, Konrada",
		"Cecylii, Wszemi³y, Stefana",
		"Adelii, Klemensa, Felicyty",
		"Flory, Emmy, Chryzogona",
		"Erazma, Katarzyny",
		"Delfiny, Sylwestra, Konrada",
		"Waleriana, Wirgiliusza, Maksyma",
		"Les³awa, Zdzis³awa, Stefana",
		"B³a¿eja, Saturnina",
		"Andrzeja, Maury, Konstantego"
	),

	new Array(
		"Natalii, Eligiusza, Edmunda",
		"Balbiny, Bibianny, Pauliny",
		"Franciszka, Ksawerego, Kasjana",
		"Barbary, Krystiana, Jana",
		"Sabiny, Krystyny, Edyty",
		"Miko³aja, Jaremy, Emiliana",
		"Marcina, Ambro¿ego, Teodora",
		"Marii, ¦wiatozara, Makarego",
		"Wies³awa Leokadii Joanny",
		"Julii, Danieli, Bogdana",
		"Damazego, Waldemara, Daniela",
		"Dagmary, Aleksandra, Ady",
		"Lucji, Otylii",
		"Alfreda, Izydora, Jana",
		"Niny, Celiny, Waleriana",
		"Albiny, Zdzis³awy, Alicji",
		"Olimpii, Lazarza, Floriana",
		"Gracjana, Bogus³awa, Laurencji",
		"Gabrieli, Dariusza, Eleonory",
		"Bogumi³y, Dominika",
		"Tomis³awa, Seweryna, Piotra",
		"Zenona, Honoraty, Franciszki",
		"Wiktorii, S³awomiry, Jana",
		"Adama, Ewy, Eweliny",
		"Anastazji, Eugenii",
		"Dionizego, Szczepana",
		"Jana, ¯anety, Maksyma",
		"Teofilii, Godzis³awa, Cezarego",
		"Dawida, Tomasza, Dominika",
		"Rainera, Eugeniusza, Irmy",
		"Sylwestra, Melanii, Mariusza"
	)
);

function PobierzImieniny(Sep, lastSep, method) {
	switch (arguments.length) {
		case 0: Sep=null;
		case 1: lastSep=null;
		case 2: method=0;
	}
	if (Sep==null) Sep=", "; if (lastSep==null) lastSep=Sep;

	var date=new Date();
	var tab=ImieninyArray[date.getMonth()][date.getDate()-1].split(", ");

	if (method==1)
		for (var i=0, ch, name, len, last; i&lt;tab.length; i++) {
			ch=(last=(name=tab[i]).substring((len=name.length)-3)).charAt(2);

			if (last=="ego") { tab[i]=name.substring(0,len-3)+"y";    continue; }
			if (last=="ñca") { tab[i]=name.substring(0,len-3)+"niec"; continue; }
			if (last=="tra") { tab[i]=name.substring(0,len-3)+"ter";  continue; }

			tab[i]=name.substring(0,len-1)+(ch=='a'?"":'a');
		}

	var str=tab[0];
	for (var i=1; i&lt;tab.length-1; i++) str+=Sep+tab[i];
	if (tab.length!=1) str+=lastSep+tab[tab.length-1];

	return str;
}

function WypiszImieniny(before, after, Sep, lastSep, method) {
	switch (arguments.length) {
		case 0: before="";
		case 1: after="";
		case 2: Sep=null;
		case 3: lastSep=null;
		case 3: method=0;
	}
	document.write(""+before+PobierzImieniny(Sep,lastSep,method)+after);
}
